"""Auto migration

Revision ID: bf1109a3c238
Revises: 
Create Date: 2025-04-27 01:57:30.863113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf1109a3c238'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('telefone_whatsapp_business', sa.String(length=20), nullable=True),
    sa.Column('tipo_estabelecimento', sa.String(length=50), nullable=True),
    sa.Column('faturamento_mensal', sa.String(length=50), nullable=True),
    sa.Column('integrar_whatsapp', sa.Boolean(), nullable=True),
    sa.Column('modo_operacao', sa.JSON(), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('usuario_painel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('documento', sa.String(length=14), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('senha_hash', sa.String(length=128), nullable=False),
    sa.Column('funcao', sa.String(length=20), nullable=False),
    sa.Column('loja_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['loja_id'], ['loja.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_painel')
    op.drop_table('loja')
    # ### end Alembic commands ###
