"""Auto migration

Revision ID: 1f6256e49b82
Revises: f890834729a9
Create Date: 2025-04-21 18:38:06.848661

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1f6256e49b82'
down_revision = 'f890834729a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_index('slug')

    op.drop_table('stores')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('slug', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('tenant_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.create_index('slug', ['slug'], unique=True)

    # ### end Alembic commands ###
